language: minimal

dist: xenial

git:
  depth: 10
  quiet: true

env:
  global:
  - VERBOSE=true
  - HEADLESS=on

before_script:
- echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
# Configure ansible vault password to decrypt secrets
- echo "$VAULT_PASSWORD" > .ansible-vault-password
- if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then export DOCKER_CACHE=off; fi

deploy:
- provider: script
  skip_cleanup: true
  script: make docker-push
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: make deploy
  on:
    branch: master

cache:
  directories:
  - ~/.make
  - ~/.npm
