apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: theklarakers-ingress
  namespace: theklarakers
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: theklarakers.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: web
  namespace: theklarakers
  labels:
    run: web
spec:
  selector:
    run: web
  ports:
  - port: 80
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: web
  namespace: theklarakers
spec:
  replicas: 2
  progressDeadlineSeconds: 90
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
      - name: web
        image: jvisser/theklarakers-website:32e0706
        imagePullPolicy: Always
        ports:
        - containerPort: 80